# Generated by Django 4.0 on 2023-09-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
