# Generated by Django 4.0 on 2023-10-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
